# Generated by Django 5.2.15 on 2026-06-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="payment_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="payment_purpose",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="reference_model",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="reference_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="paymentorder",
            name="sender_address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
